plugins {
    id 'idea'
    id 'java'
    id 'fabric-loom' version '1.9-SNAPSHOT'
    id 'maven-publish'
}

version = project.plugin_version
group = project.maven_group
archivesBaseName = project.archives_base_name

configurations {
    rusherhackApi
    compileOnly.extendsFrom(rusherhackApi)
    productionRuntime {
        extendsFrom configurations.minecraftLibraries
        extendsFrom configurations.loaderLibraries
        extendsFrom configurations.minecraftRuntimeLibraries
    }
}

repositories {
    maven {
        name = "rusherhack"
        url = "https://maven.rusherhack.org/snapshots"
    }
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    
    // rusherhack api
    rusherhackApi "org.rusherhack:rusherhack-api:${project.minecraft_version}-SNAPSHOT"
    
    // mappings
    mappings loom.layered() {
        officialMojangMappings()
    }
}

// Loom configuration
loom {
    def accessWidenerFile = new File("build/tmp/${this.project.minecraft_version}/rusherhack.accesswidener")
    if (accessWidenerFile.exists()) {
        accessWidenerPath = accessWidenerFile
    }

    runConfigs.configureEach {
        ideConfigGenerated = false
    }
}

// Java 21
def targetJavaVersion = 21

java {
    sourceCompatibility = JavaLanguageVersion.of(targetJavaVersion)
    targetCompatibility = JavaLanguageVersion.of(targetJavaVersion)
    toolchain.languageVersion.set(JavaLanguageVersion.of(targetJavaVersion))
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = targetJavaVersion
}

processResources {
    inputs.property "plugin_version", project.plugin_version
    
    filesMatching("rusherhack-plugin.json") {
        expand(
            plugin_version: project.plugin_version
        )
    }
}
jar {
    manifest {
        attributes(
            "Minecraft-Version": project.minecraft_version
        )
    }
}

// Optional: update access widener
tasks.register('updateAccessWidener', Copy) {
    group = "build"
    def accessWidenerFile = zipTree(this.project.configurations.rusherhackApi.singleFile).matching {
        include "rusherhack.accesswidener"
    }.files.iterator().next()
    from(accessWidenerFile)
    into(file("build/tmp/" + this.project.minecraft_version))
}